---
title: "WeatherData"
author: "Anupriya Thirumurthy"
date: "2/7/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(viridis)
library(ggjoy)  
library(hrbrthemes)
library(ggplot2)
library(dplyr)
library(tidyr)
```

## Import Data

```{r 1}
dataPath = "/Users/anupriya/Documents/MScA_UoC/Winter2019/Capstone/GitHub_Capstone"
DAY <- read.csv(paste(dataPath,'WeatherData.csv',sep = '/'), header=TRUE)
DAY <- subset(DAY, select = -c(X, PrecipIntensity, PrecipProbability, Pressure, Sunlight, Sunlight, DewPoint))
DAY <- subset(DAY, County=='Fresno')
datetxt <- as.Date(DAY$Date,"%m/%d/%y")
DAY <- data.frame(Date = datetxt,
                 County = DAY$County,
                 State = DAY$State,
                 Temp = DAY$Temperature,
                 Year = as.numeric(format(datetxt, format = "%Y")),
                 Month = as.numeric(format(datetxt, format = "%m")),
                 Day = as.numeric(format(datetxt, format = "%d")))
unique(DAY)
```

## Define variables and functions

```{r 2}
months <- c("June","May","April","March","February")
DAY$months <- as.Date(DAY$Temp, format = "%d-%b-%y", origin = "1960-10-01") %>% months() %>% as.factor() %>% factor(., levels = months)

#scales
mins <- min(DAY$Temp)
maxs <- max(DAY$Temp)
```

```{r 3}
# create dataframe that represents 2015-2018 historical data
Past <- DAY %>%
        group_by(Year, Month) %>%
        arrange(Day) %>%
        ungroup() %>%
        group_by(Year) %>%
        mutate(newDay = seq(1, length(Day))) %>%   # label days as 1:365 (will represent x-axis)         
        ungroup() %>%
        filter(Temp != -99 & Year != 2019) %>%     # filter missing data (identified with '-99' value) & 2019 data
        group_by(newDay) %>%
        mutate(upper = max(Temp), # identify max value for each day
               lower = min(Temp), # identify min value for each day
               avg = mean(Temp),  # calculate mean value for each day
               se = sd(Temp)/sqrt(length(Temp))) %>%  # calculate standard error of mean
        mutate(avg_upper = avg+(2.101*se),  # calculate 95% CI for mean
               avg_lower = avg-(2.101*se)) %>%  # calculate 95% CI for mean
        ungroup()

# create dataframe that represents current year data
Present <- DAY %>%
        group_by(Year, Month) %>%
        arrange(Day) %>%
        ungroup() %>%
        group_by(Year) %>%
        mutate(newDay = seq(1, length(Day))) %>%  # create matching x-axis as historical data
        ungroup() %>%
        filter(Temp != -99 & Year == 2019)  # filter out missing data & select current year data
```


```{r 4}
# function to turn y-axis labels into degree formatted values
dgr_fmt <- function(x, ...) {
        parse(text = paste(x, "*degree", sep = ""))
}

# create y-axis variable
a <- dgr_fmt(seq(30,100, by=10))

# create a small dataframe to represent legend symbol for 2019 Temperature
legend_data <- data.frame(x=seq(175,182),y=rnorm(8,15,2))
```

## Create the Temperature plot for Fresno County

```{r 5}
p <- ggplot(Past, aes(newDay, Temp)) +
        theme(plot.background = element_blank(),
              panel.grid.minor = element_blank(),
              panel.grid.major = element_blank(),
              panel.border = element_blank(),
              panel.background = element_blank(),
              axis.ticks = element_blank(),
              #axis.text = element_blank(),  
              axis.title = element_blank()) +
        geom_linerange(Past, mapping=aes(x=newDay, ymin=lower, ymax=upper), colour = "wheat2", alpha=.1)

p <- p + 
        geom_linerange(Past, mapping=aes(x=newDay, ymin=avg_lower, ymax=avg_upper), colour = "wheat4")

p <- p + 
        geom_line(Present, mapping=aes(x=newDay, y=Temp, group=1)) +
        geom_vline(xintercept = 0, colour = "wheat4", linetype=1, size=1)

p <- p + 
        geom_vline(xintercept = 31, colour = "wheat4", linetype=3, size=.5) +
        geom_vline(xintercept = 59, colour = "wheat4", linetype=3, size=.5) +
        geom_vline(xintercept = 90, colour = "wheat4", linetype=3, size=.5) +
        geom_vline(xintercept = 120, colour = "wheat4", linetype=3, size=.5) +
        geom_vline(xintercept = 151, colour = "wheat4", linetype=3, size=.5) 

p <- p +
        coord_cartesian(ylim = c(30,100)) +
        scale_y_continuous(breaks = seq(30,100, by=10), labels = a) +
        scale_x_continuous(expand = c(0, 0), 
                           breaks = c(15,45,75,105,135),
                           labels = c("February", "March", "April",
                                      "May", "June"))

p <- p +
        ggtitle("Fresno's Weather in 2018") +
        theme(plot.title=element_text(face="bold",hjust=.012,vjust=.8,colour="#3C3C3C",size=20)) +
        annotate("text", x = 19, y = 98, label = "Temperature", size=4, fontface="bold")

p <- p +
        annotate("text", x = 66, y = 93, 
                 label = "Data represents average daily temperatures in Fresno County. Accessible data dates back to Feb 1, 2015.", size=3, colour="gray30") +
        annotate("text", x = 62, y = 89, 
                 label = " Data for 2019 is only available through May 19.", size=3, colour="gray30") 

print(p)
```

